name: donationapp
description: "A new Flutter project."

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

  # ✅ Latest Firebase Dependencies (Fix Version Conflicts)
  firebase_core: ^2.25.4
  firebase_auth: ^4.19.0  # Updated to latest stable version
  cloud_firestore: ^4.15.2
  firebase_storage: ^11.7.0  # Updated for better web support

  # ✅ Other Dependencies
  pdf: ^3.10.1
  printing: ^5.9.0
  location: ^5.0.3
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/  # ✅ Ensure the folder exists!

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# ✅ Flutter Launcher Icons Configuration
dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # ✅ Ensure this file exists!
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  adaptive_icon_background: "assets/icon/app_icon_background.png"
  min_sdk_android: 23  # ✅ Required for Firebase

  web:
    generate: true
    image_path: "assets/icon/1.png"
    background_color: "#ffffff"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/icon8.png"
    icon_size: 128

  macos:
    generate: true
    image_path: "assets/icon/1.png"
