// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwX9E9YZsCIICbYxY8XFqALPHpqYhguBk',
    appId: '1:461422518001:web:56d1e3e1646af5122a1350',
    messagingSenderId: '461422518001',
    projectId: 'food-donation-ceafc',
    authDomain: 'food-donation-ceafc.firebaseapp.com',
    storageBucket: 'food-donation-ceafc.firebasestorage.app',
    measurementId: 'G-7HQX3VBN23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqW4DIx4b9H5r86VVW1Gy2-Hhl1OXWf8I',
    appId: '1:461422518001:android:8585d754914a7bf12a1350',
    messagingSenderId: '461422518001',
    projectId: 'food-donation-ceafc',
    storageBucket: 'food-donation-ceafc.firebasestorage.app',
  );
}
